### ISSUE TITLE
[feature] No recoil

### ISSUE THREAD

**Issue by WhosOn** [NullHooks/NullHooks#50]
Dudeee i just thought of this rn. a cool feature would be "No Recoil". aka a script. or whatever.

If you want me to keep giving you guys ideas i can.

**Comment by Navoichyk** [comment]
> Dudeee i just thought of this rn. a cool feature would be "No Recoil". aka a script. or whatever.
> 
> If you want me to keep giving you guys ideas i can.

Honestly, those kind of suck. Unless they are like perfected for each gun… or just like cancel recoil all together. Mainly because they’re bipolar

**Comment by rrhyast** [comment]
> Dudeee i just thought of this rn. a cool feature would be "No Recoil". aka a script. or whatever.
> 
> If you want me to keep giving you guys ideas i can.

Actually there is no recoil for csgo rn.
The Alternative is RCS (Recoil Control System) that has visible shooting pattern & make you get caught instantly by players if you don't set it properly.

people don't understand the difference between RCS & No recoil, and this damage my brain cells.

**Comment by r4v10l1** [comment]
Added todo item in 2f2314ef8147ff1cf724ac7ca10d064f957e035d
