### ISSUE TITLE
[feature] scaleform 

### ISSUE THREAD

**Issue by MAHMA787** [NullHooks/NullHooks#52]
hello I think it would be cool if u guys implement this https://github.com/TeamSCALEFORM/scaleform into ur source

**Comment by r4v10l1** [comment]
I saw some people talking about it and the [UC post](https://www.unknowncheats.me/forum/counterstrike-global-offensive/507987-scaleform-hud.html), but I haven't really looked into how it works or how to implement it.

I will keep it in mind.

**Comment by r4v10l1** [comment]
Added todo item in 2f2314ef8147ff1cf724ac7ca10d064f957e035d
