### ISSUE TITLE
[misc] Cheat is leaking something which makes it autodetected as a cheat while joining community servers

### ISSUE THREAD

**Issue by DemonLoverHvH** [NullHooks/NullHooks#69]
Like the title says you get insta banned from servers with the AntiDLL plugin which is most likely caused by event listeners as you will be able to see [here](https://github.com/JDW1337/AntiDLL/blob/main/extension.cpp#L33) 

And doing something like this should fix it:
```cpp
for (int i=0; i < m_GameEvents.Count(); i++) // what we want to listen to 
{
    CGameEventDescriptor &descriptor = m_GameEvents[i];
    if ( descriptor.local )
    {
        continue;  // event is not networked
    }
} 
```

**Comment by r4v10l1** [comment]
The cheat doesn't have an event listener, instead uses `FireEventIntern`. See #36

**Comment by DemonLoverHvH** [comment]
> The cheat doesn't have an event listener, instead uses `FireEventIntern`. See #36

hmm then idk what's causing it
