### ISSUE TITLE
Double collideable_t class

### ISSUE THREAD

**Issue by Ceaco1337** [NullHooks/NullHooks#70]
Original (Works perfectly fine)
https://github.com/NullHooks/NullHooks/blob/6c9f6df4e2d519a7e0525a16e4998c90b7c5303e/src/source-sdk/classes/collideable.hpp#L3

(Why?)
https://github.com/NullHooks/NullHooks/blob/6c9f6df4e2d519a7e0525a16e4998c90b7c5303e/src/source-sdk/classes/entities.hpp#L314

The 1 time it's referenced (thankfully, no massive renames)
https://github.com/NullHooks/NullHooks/blob/6c9f6df4e2d519a7e0525a16e4998c90b7c5303e/src/core/features/visuals/player_esp.cpp#L8

**Comment by r4v10l1** [comment]
@hBuffer (Now missing) added that and I didn't notice it was duplicate. I will try to fix it asap, thank you for reporting the issue.

Could you add me on discord at: `8dcc#7423`?

**Comment by r4v10l1** [comment]
Fixed in f5a4bc753d7525de9fcc128d75fdf9724e1dd6b0
