### ISSUE TITLE
[fix] Crash fix (i guess)

### ISSUE THREAD

**Issue by Utkukck11** [NullHooks/NullHooks#86]
file: csgo.hpp
line 51 
replace sig_fire_event signature with "55 8B EC 83 E4 F8 83 EC 0C 8B C1"
file: netvars.cpp
line 73
replace uintptr_t with "uint32_t"
its can be wrong but working for me

**Comment by Utkukck11** [comment]
looks like still crashing hmm

**Comment by r4v10l1** [comment]
I was going to write a comment about the fire_event signature now and I saw the new issue. Thanks for taking the time.

**Comment by Utkukck11** [comment]
Yeah i will look again when i got free time thanks

**Comment by r4v10l1** [comment]
I found a crash and fixed it in e6e0d67
