### ISSUE TITLE
[feature] Can you add a wall hack

### ISSUE THREAD

**Issue by Matrix-CN** [NullHooks/NullHooks#87]
Can you add a wall hack？
I would appreciate it if I could

**Comment by r4v10l1** [comment]
The cheat does have plenty of visual features, please read the [README.md](https://github.com/NullHooks/NullHooks/blob/main/README.md) before submitting this issues.

In case you don't know, you can open the menu with 
`Insert` (maybe you thought the cheat only had bhop and watermark...)
